---
- name: Install iptables-persistent
  apt: name=iptables-persistent state=latest

- name: Get ip6tables rules
  shell: /sbin/ip6tables -L
  register: ip6tablesrules
  always_run: yes

- name: Add ipv6 conntrack rule
  command: /sbin/ip6tables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT -m comment --comment "Conntrack"
  when: ip6tablesrules.stdout.find("Conntrack") == -1

- name: Add ipv6 ssh iptables rule
  command: /sbin/ip6tables -A INPUT -p tcp --dport 22 -j ACCEPT -m comment --comment "SSH"
  when: ip6tablesrules.stdout.find("SSH") == -1

- name: Add ipv6 nginx iptables rule
  command: /sbin/ip6tables -I INPUT -p tcp --dport 80 -j ACCEPT -m comment --comment "Nginx_HTTP"
  when: ip6tablesrules.stdout.find("Nginx_HTTP") == -1

- name: Add ipv6 nginx ssl iptables rule
  command: /sbin/ip6tables -I INPUT -p tcp --dport 443 -j ACCEPT -m comment --comment "Nginx_SSL"
  when: ip6tablesrules.stdout.find("Nginx_SSL") == -1

- name: Add ipv6 local interface iptables rule
  command: /sbin/ip6tables -I INPUT -i lo -j ACCEPT -m comment --comment "Local"
  when: ip6tablesrules.stdout.find("Local") == -1

- name: Add ipv6 socket.io iptables rule
  command: /sbin/ip6tables -I INPUT -p tcp --dport 4000 -j ACCEPT -m comment --comment "SocketIO"
  when: ip6tablesrules.stdout.find("SocketIO") == -1

- name: Add ipv6 default iptables policy
  command: /sbin/ip6tables -P INPUT DROP

- name: Save ip6tables
  shell: /sbin/ip6tables-save > /etc/iptables/rules.v6