---
- name: Create unsplash-downloader directory
  file: path=/opt/unsplash-downloader state=directory owner=unsplash group=unsplash

- name: Clone the repo
  shell: "cd /opt/unsplash-downloader && su unsplash -c 'git clone https://github.com/DMarby/unsplash-downloader.git /opt/unsplash-downloader'"

- name: Set git name
  shell: cd /opt/unsplash-downloader && su unsplash -c 'git config --global user.name "Unsplash"'

- name: Set git email
  shell: cd /opt/unsplash-downloader && su unsplash -c 'git config --global user.email "david@dmarby.se"'

- name: Install dependencies for unsplash-downloader
  shell: "su unsplash -c 'cd /opt/unsplash-downloader && npm install'"

- name: Copy unsplash-downloader config
  copy: src=files/unsplash-downloader.conf dest=/opt/unsplash-downloader/config.js owner=unsplash group=unsplash

- name: Add cronjob for unsplash-downloader
  action: 'cron name="unsplash-downloader" special_time=daily user=unsplash job="cd /opt/unsplash-downloader && /usr/bin/node index.js"'