---
- name: Upgrade existing packages
  apt: upgrade=full update_cache=yes

- name: Prefer ipv4
  lineinfile: dest=/etc/gai.conf line="precedence ::ffff:0:0/96  100" state="present"

- name: Prefer ipv4
  lineinfile: dest=/etc/network/interfaces regexp="^.*dns-nameservers.*$" line="        dns-nameservers 8.8.8.8 8.8.4.4 2001:4860:4860::8844 2001:4860:4860::8888" state="present"

- name: Create unsplash user
  user: name=unsplash shell=/bin/bash createhome=yes system=yes

- name: Create ssh directory
  file: path=/home/unsplash/.ssh state=directory owner=unsplash group=unsplash

- name: Copy private key
  copy: src=files/unsplash_rsa dest=/home/unsplash/.ssh/id_rsa owner=unsplash group=unsplash mode=0400

- name: Disable password login for ssh
  lineinfile: dest=/etc/ssh/sshd_config state=absent regexp="^PasswordAuthentication yes"

- name: Disable password login for ssh
  lineinfile: dest=/etc/ssh/sshd_config line="PasswordAuthentication no"
  notify:
    - restart sshd

- name: Install required packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - curl
    - git
    - vnstat
    - htop
    - pkg-config


- name: Add github to known_hosts file
  shell: "su unsplash -c 'ssh-keyscan -t rsa github.com > /home/unsplash/.ssh/known_hosts'"

- name: Add dmarby to known_hosts file
  shell: "su unsplash -c 'ssh-keyscan -t rsa dmarby.se > /home/unsplash/.ssh/known_hosts'"

- name: Create photos folder
  file: path=/opt/photos state=directory owner=unsplash group=unsplash

- name: Clone photos repo
  shell: "cd /opt/photos && su unsplash -c 'git clone upload@dmarby.se:photos.git /opt/photos'"
