---
- name: reload initctl
  command: initctl reload-configuration

- name: restart nginx
  service: name=nginx state=restarted

- name: start unsplash-it
  command: initctl start unsplash-it

- name: restart unsplash-it
  service: name=unsplash-it state=restarted

- name: restart sshd
  service: name=ssh state=restarted
